
###
GET http://localhost:5555/emplist


###
POST http://localhost:5555/emplist
Content-Type: application/json

{
    "empname":"Mohit",
    "dept":"HR",
    "city":"Delhi",
    "salary":"10000"
}


###
DELETE http://localhost:5555/productlist/651a9b90f2b9c6ae2e98bf23



###
PATCH http://localhost:5555/emplist
Content-Type: application/json

{
    "empname":"Satya",
    "dept":"HR",
    "city":"Kolkata",
    "salary":"12000",
    "id":"65102bffb2155b8db4088d36"
}


###
POST http://localhost:5555/productlist
Content-Type: application/json

{
    "productname":"Mango Green",
    "productprice":"200",
    "productqty":"30",
    "productphoto":"2.jpg"
}


###
PUT http://localhost:5555/productlist/65213aa802589abcbcb05b6f



###
DELETE http://localhost:5555/productlist/651a9b90f2b9c6ae2e98bf23